// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ-EZ56lXzVwLCeXEhcozAt57GI5ioPRo',
    appId: '1:903677784761:web:5619ed2015157b7a54e168',
    messagingSenderId: '903677784761',
    projectId: 'fluttersupervielle',
    authDomain: 'fluttersupervielle.firebaseapp.com',
    storageBucket: 'fluttersupervielle.appspot.com',
    measurementId: 'G-NLVZ281HXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNPPUiYbtXqGvmXNxENEpVZFhm-1tiZ0M',
    appId: '1:903677784761:android:ca67b29c50074aff54e168',
    messagingSenderId: '903677784761',
    projectId: 'fluttersupervielle',
    storageBucket: 'fluttersupervielle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjhxBQ6j-g7lMEGYHodMh0UcgM-ANXqxw',
    appId: '1:903677784761:ios:046099848e96163554e168',
    messagingSenderId: '903677784761',
    projectId: 'fluttersupervielle',
    storageBucket: 'fluttersupervielle.appspot.com',
    iosBundleId: 'com.example.flutterApplicationAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjhxBQ6j-g7lMEGYHodMh0UcgM-ANXqxw',
    appId: '1:903677784761:ios:ecfc41c26ecf5f5954e168',
    messagingSenderId: '903677784761',
    projectId: 'fluttersupervielle',
    storageBucket: 'fluttersupervielle.appspot.com',
    iosBundleId: 'com.example.flutterApplicationAnalytics.RunnerTests',
  );
}
